### ISSUE TITLE
Better support for using Operator Aliases

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/DiagrammaticEquations.jl#35]
The goal here is to use familiar `Div, Grad, Curl, Lapl` operators in their familiar role in vector calculus. What support do we need in the Decapodes language for that? Probably and alias operator like `:=`

```julia
oscillator = @decapode begin
  X::Form0
  V::Form0
  div := ⋆⋅d
  
  ∂ₜ(X) == V
  ∂ₜ(V) == -k(X) + div(V)
end
```

Then we can update all the docs examples to use these operators when appropriate. We can't uniformly introduce a exterior calculus definitions of div, grad, curl because of things like how gradient of Pressure should be `dP` but gradient of concentration should be `⋆dC`. Unless we can dispatch on expected return type in the type inference code, I think that we can just introduce a manual aliasing operator into the decapode macro, and then have local aliases in each example.

**Comment by lukem12345** [comment]
It sounds like this issue is about specifying a DSL for what is done when we “open operators” in Decapodes https://github.com/AlgebraicJulia/Decapodes.jl/blob/55ff02b26497ddc0122a9fbd8b6f0e89a7047ebc/src/operators.jl#L160

Is there anything in the AlgebraicJulia ecosystem that already has a DSL that parses little functions into any data structure that is easy to iterate over? This sounds like a directed wiring diagram.

**Comment by lukem12345** [comment]
An attempt at this feature was made a long time ago with AlgebraicRewriting, but that failed due to [reasons specified here](https://github.com/AlgebraicJulia/Decapodes.jl/pull/86#issuecomment-1322301072).

**Comment by lukem12345** [comment]
Or, we could go the `oapply` route instead, and implement this feature by way of issue #36 , which ought to be speedier.
